src/Entity/Candidate.php
<?php

namespace App\Entity;

use App\Repository\CandidateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CandidateRepository::class)]
class Candidate
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $political_party = null;

    #[ORM\Column(length: 255)]
    private ?string $number_list = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fileImage = null;

    #[ORM\OneToMany(mappedBy: 'candidate', targetEntity: Electeur::class)]
    private Collection $vote;

    #[ORM\Column(length: 255,nullable: true)]
    private ?string $filename = null;

    #[ORM\OneToOne(cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Electeur $electeur = null;

    public function __construct()
    {
        $this->vote = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPoliticalParty(): ?string
    {
        return $this->political_party;
    }

    public function setPoliticalParty(string $political_party): static
    {
        $this->political_party = $political_party;

        return $this;
    }

    public function getNumberList(): ?string
    {
        return $this->number_list;
    }

    public function setNumberList(string $number_list): static
    {
        $this->number_list = $number_list;

        return $this;
    }

    public function getFileImage(): ?string
    {
        return $this->fileImage;
    }

    public function setFileImage(?string $fileImage): static
    {
        $this->fileImage = $fileImage;

        return $this;
    }

    /**
     * @return Collection<int, Electeur>
     */
    public function getVote(): Collection
    {
        return $this->vote;
    }

    public function addVote(Electeur $vote): static
    {
        if (!$this->vote->contains($vote)) {
            $this->vote->add($vote);
            $vote->setCandidate($this);
        }

        return $this;
    }

    public function removeVote(Electeur $vote): static
    {
        if ($this->vote->removeElement($vote)) {
            // set the owning side to null (unless already changed)
            if ($vote->getCandidate() === $this) {
                $vote->setCandidate(null);
            }
        }

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): static
    {
        $this->filename = $filename;

        return $this;
    }

    public function getElecteur(): ?Electeur
    {
        return $this->electeur;
    }

    public function setElecteur(Electeur $electeur): static
    {
        $this->electeur = $electeur;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Candidate;
use App\Entity\Electeur;
use App\Repository\CandidateRepository;
use App\Repository\ElecteurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{

    public function __construct(private readonly ElecteurRepository $repository,private readonly CandidateRepository $candidateRepository,private readonly EntityManagerInterface $em)
    {
    }

    #[Route('/', name: 'app_home')]
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
        ]);
    }

    #[Route('/vote', name: 'vote_candidat',methods: ['POST'])]
    public function ratePresident(Request $request): Response
    {
        $candidate = $this->candidateRepository->findOneBy(['number_list'=>$request->get('_president')]);
        $electeur = $this->repository->findOneBy(['id'=>$request->get('_electeur')]);

        $candidate->setElecteur($electeur);
        $this->em->flush();

        $this->addFlash('success',"Voaray ny safidinao");

        return $this->redirectToRoute('app_home');
    }

    #[Route('/login_electeur', name: 'login-electeur', methods: ['GET','POST'])]
    public function logElector(Request $request,CandidateRepository $repository): Response
    {

        $electeur = $this->repository->findOneBy(['name'=>$request->get('_username')]);
        $username = $request->get('_username');
        if($electeur)
        {

            if($electeur->getCinNumber() === $request->get('_cin') && $electeur->getCandidate() === null)
            {
                $candidates = $repository->findAll();
                return $this->render('home/index.candidate.html.twig',['electeur'=>$electeur,'candidates'=>$candidates]);

            }
        }

        return $this->render('electeur.html.twig',['username'=>$username]);
    }
}

templates/home/index.candidate.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    E-fidy - Lisitra
{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<h1 class="mb-4 text-4xl text-center font-extrabold text-gray-600 md:text-5xl lg:text-6xl dark:text-gray mt-8 ">Lisitrin'ny kandida ho fidiana</h1>

<div class="px-3 md:lg:xl:px-40 border-t border-b py-20 bg-opacity-10" style="background-image: url('https://www.toptal.com/designers/subtlepatterns/uploads/dot-grid.png') ;">
 
    <div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 border ">
        {% for candidate in candidates %}
        <div class="max-w-md py-4 px-8 shadow-lg rounded-lg my-20">
            <div class="flex justify-center md:justify-end -mt-16">
            <img class="w-40 h-40 object-cover rounded-full border-2 border-indigo-500" src="https://images.unsplash.com/photo-1499714608240-22fc6ad53fb2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80">
            </div>
            <div>
                <h2 class="text-gray-800 text-3xl font-semibold">{{candidate.numberList}}</h2>
                <h2 class="text-gray-800 text-3xl font-semibold">{{candidate.name}} </h2>
                <h2 class="text-gray-800 text-3xl font-semibold">{{candidate.firstname}}</h2>
                <p class="mt-2 text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                     Quae dolores deserunt ea doloremque natus error
                </p>
                <hr class="mt-3 border-b-1 border-gray-200">
                <form method="POST" action="{{ path('vote_candidat') }}">
                    <input type="hidden" name="_president" value="{{ candidate.numberList }}">
                    <input type="hidden" name="_electeur" value="{{ electeur.id }}">
                <div class="flex justify-center items-center py-2 mt-3 text-sm font-medium">
                    <button type="submit" class="text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200  font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">FIDIKO</button>
                </div>
                </form>
            </div>
            <div class="flex justify-end ">
                <a href="#" class="text-xl font-medium text-indigo-500">Mombamomba Azy</a>
            </div>
        </div>
        {% endfor %}


    </div>
</div>
    {% include 'component/footer.html.twig' %}



<!-- </div> -->
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}E-Fidy
{% endblock %}

{% block body %}


	{# <nav class="bg-green-400 p-4 shadow-2xl ">
																																																																																																													<div class="container  flex justify-between items-center">
																																																																																																														<img src="/assets/images/flag.png" class="rounded-full w-20" alt="Description de l'image">
																																																																																																														<a href="#" class="text-white text-2xl font-semibold">ELECTION</a>
																																																																																																														<div class="flex space-x-14">
																																																																																																															<a href="#" class="text-white hover:text-blue-300">Accueil</a>
																																																																																																															<a href="#" class="text-white hover:text-blue-300">À propos</a>
																																																																																																															<a href="#" class="text-white hover:text-blue-300">Services</a>
																																																																																																															<a href="#" class="text-white hover:text-blue-300">Contact</a>
																																																																																																														</div>
																																																																																																														<div class="relative">
																																																																																																															<input type="search" placeholder="Rechercher..." class="bg-white h-10 px-5 pr-10 rounded-full text-sm focus:outline-none">
																																																																																																															<button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
																																																																																																																<Icon-feather name="search"></Icon-feather>
																																																																																																															</button>
																																																																																																														</div>
																																																																																																													</div>
																																																																																																												</nav> #}
<div class="md:min-h-screen bg-green-50 md:max-h-screen">

	<div
			class="flex container py-4 relative sm:min-h-screen justify-center  md:max-h-screen flex-row gap-4 mx-auto">
		{# <div
																																																																																																																																																																																																									class="bg-cover bg-center backdrop-blur-md w-1/2 opacity-60" style="background-image: url('/assets/images/carte.png');">
																																																																																																																																																																																																									<!-- Contenu de votre page -->


																																																																																																																																																																																																									<div>
																																																																																																																																																																																																										<!-- Contenu de la div de gauche -->
																																																																																																																																																																																																										<div class="flex items-center justify-center h-screen">
																																																																																																																																																																																																											<div class="text-5xl text-center  font-bold">
																																																																																																																																																																																																												<span class="">Cast your vote for the finest</span>
																																																																																																																																																																																																												<span class="text-red-600">candidates</span>
																																																																																																																																																																																																											</div>
																																																																																																																																																																																																										</div>
																																																																																																																																																																																																									</div>
																																																																																																																																																																																																								</div> #}
		<a href="{{ path('login-electeur') }}"
				class="bg-green-400 hover:scale-95 hover:bg-green-500 duration-300 cursor-pointer flex items-center justify-center rounded shadow p-6 max-w-md  text-center w-1/2">
			<!-- Icône en haut -->
			<div class="text-3xl text-white flex items-center flex-col">
				<Icon-feather size="175" name="envelop"></Icon-feather>
				<span class="text-bold mt-8 uppercase">Voter</span>
			</div>


		</a>


		<a href=""
				class="bg-red-400 hover:scale-95 hover:bg-red-500 duration-300 cursor-pointer flex items-center justify-center rounded shadow p-6 max-w-md  text-center w-1/2">
			<!-- Icône en haut -->
			<div class="text-3xl text-white flex items-center flex-col">
				<Icon-feather size="175" name="eye"></Icon-feather>
				<span class="text-bold mt-8 uppercase">voir les candidats
				</span>
			</div>


		</a>
	</div>
</div>
	{# </div>
																																																																												<div class="">
																																																																													<div class="grid grid-cols-2 md:grid-cols-4 gap-4 p-4">
																																																																														<div class="bg-white border rounded-lg shadow-md p-4">
																																																																															<h2 class="text-xl font-semibold">
																																																																																<Icon-feather name="save"></Icon-feather>
																																																																															</h2>
																																																																															<p>Contenu de la carte 1</p>
																																																																														</div>
																																																																											
																																																																														<div class="bg-white border rounded-lg shadow-md p-4">
																																																																															<h2 class="text-xl font-semibold">Carte 2</h2>
																																																																															<p>Contenu de la carte 2</p>
																																																																														</div>
																																																																											
																																																																														<div class="bg-white border rounded-lg shadow-md p-4">
																																																																															<h2 class="text-xl font-semibold">Carte 3</h2>
																																																																															<p>Contenu de la carte 3</p>
																																																																														</div>
																																																																											
																																																																														<div class="bg-white border rounded-lg shadow-md p-4">
																																																																															<h2 class="text-xl font-semibold">Carte 4</h2>
																																																																															<p>Contenu de la carte 4</p>
																																																																														</div>
																																																																											
																																																																														<div class="bg-white border rounded-lg shadow-md p-4">
																																																																															<h2 class="text-xl font-semibold">Carte 5</h2>
																																																																															<p>Contenu de la carte 5</p>
																																																																														</div>
																																																																											
																																																																														<div class="bg-white border rounded-lg shadow-md p-4">
																																																																															<h2 class="text-xl font-semibold">Carte 6</h2>
																																																																															<p>Contenu de la carte 6</p>
																																																																														</div>
																																																																											
																																																																														<div class="bg-white border rounded-lg shadow-md p-4">
																																																																															<h2 class="text-xl font-semibold">Carte 7</h2>
																																																																															<p>Contenu de la carte 7</p>
																																																																														</div>
																																																																											
																																																																														<div class="bg-white border rounded-lg shadow-md p-4">
																																																																															<h2 class="text-xl font-semibold">Carte 8</h2>
																																																																															<p>Contenu de la carte 8</p>
																																																																														</div>
																																																																													</div>
																																																																											
																																																																											
																																																																												</div> #}



{% endblock %}